package mybatis.dao;

import java.util.List;
import mybatis.model.Imsi;
import mybatis.model.ImsiExample;
import org.apache.ibatis.annotations.Param;

public interface ImsiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    int countByExample(ImsiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    int deleteByExample(ImsiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    int insert(Imsi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    int insertSelective(Imsi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    List<Imsi> selectByExample(ImsiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    Imsi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    int updateByExampleSelective(@Param("record") Imsi record, @Param("example") ImsiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    int updateByExample(@Param("record") Imsi record, @Param("example") ImsiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    int updateByPrimaryKeySelective(Imsi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imsi
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    int updateByPrimaryKey(Imsi record);
}