package mybatis.model;

import java.util.Date;

public class Imsi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imsi.id
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imsi.name
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imsi.testtime
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    private Date testtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imsi.submittime
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    private Date submittime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imsi.id
     *
     * @return the value of imsi.id
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imsi.id
     *
     * @param id the value for imsi.id
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imsi.name
     *
     * @return the value of imsi.name
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imsi.name
     *
     * @param name the value for imsi.name
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imsi.testtime
     *
     * @return the value of imsi.testtime
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    public Date getTesttime() {
        return testtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imsi.testtime
     *
     * @param testtime the value for imsi.testtime
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    public void setTesttime(Date testtime) {
        this.testtime = testtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imsi.submittime
     *
     * @return the value of imsi.submittime
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imsi.submittime
     *
     * @param submittime the value for imsi.submittime
     *
     * @mbggenerated Mon Apr 27 11:36:37 CST 2015
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }
}